### ISSUE TITLE
cljest.compilation/watch throwing "Invalid blocking call in dispatch thread"

### ISSUE THREAD

**Issue by lucascebertin** [pitch-io/cljest#46]
I've created a minimal project following the ["installation"](https://github.com/pitch-io/cljest/blob/master/docs/installation.md) that runs smoothly in a Linux (Manjaro KDE kernel 6.1.55-1) but not on MacOS (M1 Sonoma 14.1.1 (23B81)). 

Linux clojure version:
`Clojure CLI version 1.11.1.1386`

MacOS clojure version:
`Clojure CLI version 1.11.1.1323`

The very same project on MacOS gives me the error:

```bash
Exception in thread "async-dispatch-5" java.lang.IllegalStateException: Invalid blocking call in dispatch thread
        at clojure.core.async.impl.dispatch$check_blocking_in_dispatch.invokeStatic(dispatch.clj:29)
        at clojure.core.async.impl.dispatch$check_blocking_in_dispatch.invoke(dispatch.clj:26)
        at clojure.core.async$fn__14076.invokeStatic(async.clj:125)
        at clojure.core.async$fn__14076.invoke(async.clj:125)
        at cljest.compilation.shadow$get_1st_msg_on_chan.invokeStatic(shadow.clj:83)
        at cljest.compilation.shadow$get_1st_msg_on_chan.doInvoke(shadow.clj:68)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at cljest.compilation.shadow$get_compilation_result.invokeStatic(shadow.clj:194)
        at cljest.compilation.shadow$get_compilation_result.invoke(shadow.clj:189)
        at cljest.compilation.server$compile_and_update_build_status_BANG_.invokeStatic(server.clj:50)
        at cljest.compilation.server$compile_and_update_build_status_BANG_.invoke(server.clj:37)
        at cljest.compilation.server$start_server_BANG_$fn__33681$state_machine__13938__auto____33686$fn__33688.invoke(server.clj:164)
        at cljest.compilation.server$start_server_BANG_$fn__33681$state_machine__13938__auto____33686.invoke(server.clj:164)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
        at cljest.compilation.server$start_server_BANG_$fn__33681.invoke(server.clj:164)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__7712$fn__7713.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "async-dispatch-6" java.lang.IllegalStateException: Invalid blocking call in dispatch thread
        at clojure.core.async.impl.dispatch$check_blocking_in_dispatch.invokeStatic(dispatch.clj:29)
        at clojure.core.async.impl.dispatch$check_blocking_in_dispatch.invoke(dispatch.clj:26)
        at clojure.core.async$fn__14076.invokeStatic(async.clj:125)
        at clojure.core.async$fn__14076.invoke(async.clj:125)
        at shadow.cljs.devtools.server.worker$start.invokeStatic(worker.clj:178)
        at shadow.cljs.devtools.server.worker$start.invoke(worker.clj:98)
        at shadow.cljs.devtools.server.supervisor$start_worker.invokeStatic(supervisor.clj:30)
        at shadow.cljs.devtools.server.supervisor$start_worker.invoke(supervisor.clj:19)
        at shadow.cljs.devtools.api$start_worker.invokeStatic(api.clj:117)
        at shadow.cljs.devtools.api$start_worker.invoke(api.clj:113)
        at shadow.cljs.devtools.api$watch_STAR_.invokeStatic(api.clj:187)
        at shadow.cljs.devtools.api$watch_STAR_.invoke(api.clj:173)
        at shadow.cljs.devtools.api$watch.invokeStatic(api.clj:213)
        at shadow.cljs.devtools.api$watch.invoke(api.clj:200)
        at cljest.compilation.shadow$start_watching.invokeStatic(shadow.clj:233)
        at cljest.compilation.shadow$start_watching.invoke(shadow.clj:231)
        at cljest.compilation.server$start_server_BANG_$fn__33707$state_machine__13938__auto____33712$fn__33714.invoke(server.clj:165)
        at cljest.compilation.server$start_server_BANG_$fn__33707$state_machine__13938__auto____33712.invoke(server.clj:165)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
        at cljest.compilation.server$start_server_BANG_$fn__33707.invoke(server.clj:165)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__7712$fn__7713.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Can it be any mistake on my side?
Any ideas of what can I try on my side?

**Comment by lucascebertin** [comment]
I don't know what exactly happened but adding a `deps.edn` and running with `clj -X cljest.compilation/watch` instead of `lein run -m cljest.compilation/watch {}` works.

Probably this can be closed but I'm a little bit confused
